### ISSUE TITLE
Add generated PDF to `.gitignore`

### ISSUE THREAD

**Issue by NicMcPhee** [erp12/inductive-program-synthesis-comparison#1]
I usually add the generated PDF (`paper/softsynth.pdf` in this case) in `.gitignore`. Otherwise it tends to create merge conflicts in `git`, since `git` can't "merge" changes to the PDF.

We can then attach the generated PDF to releases when, e.g., we do the initial submission.

This said, some people like having the generated PDF, because they can you read the current draft of the paper without having to checkout and build.

I can do this if we want, but I wanted to check in before just smashing around changing things.

**Comment by erp12** [comment]
I agree that merges + pdf = 👎 .
Just made this change.
